/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 * This project uses @Incubating APIs which are subject to change.
 */

 plugins {
     id("com.github.johnrengelman.shadow") version "8.1.1"
     id("java")
 }

 repositories {
     mavenCentral()
 }


 dependencies {
     implementation(files("../build/libs/snappy-java.jar"))
     implementation("com.code-intelligence:jazzer-junit:0.22.1")
     implementation("com.code-intelligence:jazzer-api:0.22.1")
 }
